### ISSUE TITLE
IMS build fails due to missing liblinear 1.51

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-wsd#79]
Builds of de.tudarmstadt.ukp.dkpro.wsd.supervised.ims-gpl are failing due to the inexplicable disappearance of liblinear 1.51.  (Perhaps whatever repository hosted this artifact has removed it?)

**Comment by reckart** [comment]
Can you upgrade to a liblinear version from Maven Central? We recently negotiated a belated release of liblinear 1.7.1 on Maven Central due to a dependency in matetools/DKPro Core. Maybe that works for you as well?

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.bwaldvogel%22%20AND%20a%3A%22liblinear%22

**Comment by logological** [comment]
Yes, I've just pushed a commit that upgrades the dependency to 1.7.  Strange that GitHub didn't automatically reference the commit here, since I mentioned this issue in the commit description.

**Comment by reckart** [comment]
You need to say `#79`(with the hash).

**Comment by logological** [comment]
Fixed by Commit af396d3.
